### ISSUE TITLE
白色主题的代码块功能失效

### ISSUE THREAD

**Issue by mancuoj** [T-miracle/vitepress-plugin-codeblocks-fold#2]
![image](https://github.com/T-miracle/vitepress-plugin-codeblocks-fold/assets/45707684/1025dc65-6619-43d2-a0d8-dda587329af7)

配置是 

```ts
markdown: {
  theme: {
    light: 'vitesse-light',
    dark: 'vitesse-dark',
  },
...
...
```

**Comment by T-miracle** [comment]
> ![image](https://user-images.githubusercontent.com/45707684/239809270-1025dc65-6619-43d2-a0d8-dda587329af7.png)
> 
> 配置是
> 
> ```ts
> markdown: {
>   theme: {
>     light: 'vitesse-light',
>     dark: 'vitesse-dark',
>   },
> ...
> ...
> ```

好的，这两天抽点时间做一下适配

**Comment by T-miracle** [comment]
@mancuoj 以兼容多主题，请升级至 1.12.15 版本
