### ISSUE TITLE
新版本深色颜色分层 

### ISSUE THREAD

**Issue by mancuoj** [T-miracle/vitepress-plugin-codeblocks-fold#3]
又来了，新版本新"feature"

浅色修好了，但深色这个看着好奇怪，我不知道是不是我主题配置的问题，[项目代码](https://github.com/mancuoj/fe)

![image](https://github.com/T-miracle/vitepress-plugin-codeblocks-fold/assets/45707684/885af147-6c6d-4516-b664-adfb7320a7f3)

**Comment by T-miracle** [comment]
@mancuoj ![image](https://github.com/T-miracle/vitepress-plugin-codeblocks-fold/assets/44044121/9b3d5812-c24d-4051-98c6-ca0e3787ad28) 问题已找到，是因为你的主体配色带有rgba透明属性的颜色了，而按钮层和遮罩层是覆盖在代码块上的，从而颜色穿透导致了两个透明属性叠加，所以显示不太正常，我看下这周末有时间修复这个问题吧

**Comment by T-miracle** [comment]
@mancuoj 透明色叠加这个问题有点难以解决，为了看起来不是那么奇怪，目前就是如果是rgba色的话就把那层渐变色的遮罩层关掉，这样看起来会正常点，以后再想想其他的办法解决这个问题了

现在你可以更新新版看看效果

**Comment by mancuoj** [comment]
![image](https://github.com/T-miracle/vitepress-plugin-codeblocks-fold/assets/45707684/204392a6-7e66-42da-811b-cde494631354)

感谢，但是新版 build 失败

**Comment by T-miracle** [comment]
@mancuoj 再更新试试

**Comment by mancuoj** [comment]
还是分层，算了我妥协了，我把透明度改到0.7就没有分层了
