### ISSUE TITLE
显示代码行数问题

### ISSUE THREAD

**Issue by TengWu98** [T-miracle/vitepress-plugin-codeblocks-fold#5]
您好~
在markdown配置中选择显示行数的时候：
![image](https://github.com/T-miracle/vitepress-plugin-codeblocks-fold/assets/125466921/74d5aed2-233c-4a0b-8586-70c7e6cccaa9)
使用插件行数没有折叠起来

**Comment by T-miracle** [comment]
已确认BUG，感谢反馈

**Comment by T-miracle** [comment]
已更新，请升级至最新版本
