### ISSUE TITLE
首页actions中新增link为指定文件的指定标题时（例如link: /guide/config#action），跳转指定页面会导致跳转位置不对应

### ISSUE THREAD

**Issue by shen830** [T-miracle/vitepress-plugin-codeblocks-fold#7]
大佬有个问题是，首页hero下actions中新增link为指定文件的指定标题时（例如link: /guide/config#action），跳转指定页面会导致跳转位置不对应。正常应该跳转到config.md文件的action标题上，但是由于前面有折叠的代码块，导致跳转到了config.md文件的其他标题上

**Comment by T-miracle** [comment]
> 大佬有个问题是，首页hero下actions中新增link为指定文件的指定标题时（例如link: /guide/config#action），跳转指定页面会导致跳转位置不对应。正常应该跳转到config.md文件的action标题上，但是由于前面有折叠的代码块，导致跳转到了config.md文件的其他标题上

抱歉，最近比较忙，没注意到您的问题。
我刚更新了一版，你可以更新试试看。

**Comment by shen830** [comment]
> 我刚更新了一版，你可以更新试试看。

感谢大佬抽空解决问题，我试了下可以解决，但我个人觉得不加behavior: 'smooth'比较好，加了这个观感上感觉有点慢回弹，还是想一下就到指定位置

**Comment by T-miracle** [comment]
> > 我刚更新了一版，你可以更新试试看。
> 
> 感谢大佬抽空解决问题，我试了下可以解决，但我个人觉得不加behavior: 'smooth'比较好，加了这个观感上感觉有点慢回弹，还是想一下就到指定位置

嗯行，我晚点抽个时间再优化一下

**Comment by T-miracle** [comment]
> > 我刚更新了一版，你可以更新试试看。
> 
> 感谢大佬抽空解决问题，我试了下可以解决，但我个人觉得不加behavior: 'smooth'比较好，加了这个观感上感觉有点慢回弹，还是想一下就到指定位置

应该可以了

**Comment by dcdy** [comment]
> > > 我刚更新了一版，你可以更新试试看。
> > 
> > 
> > 感谢大佬抽空解决问题，我试了下可以解决，但我个人觉得不加behavior: 'smooth'比较好，加了这个观感上感觉有点慢回弹，还是想一下就到指定位置
> 
> 应该可以了

可以了👌，感谢大佬

**Comment by shen830** [comment]
> > > 我刚更新了一版，你可以更新试试看。
> > 
> > 
> > 感谢大佬抽空解决问题，我试了下可以解决，但我个人觉得不加behavior: 'smooth'比较好，加了这个观感上感觉有点慢回弹，还是想一下就到指定位置
> 
> 应该可以了

可以了👌，感谢大佬
